INSERT IGNORE INTO products (id, name, price, attributes)
VALUES
    (1, 'iPhone 16 Pro', 28990000,
     '{"brand":"Apple","category":"Phone","storage":"256GB","warranty":"12 months"}'),
    (2, 'Samsung Galaxy S25 Ultra', 26990000,
     '{"brand":"Samsung","category":"Phone","storage":"256GB","warranty":"12 months"}'),
    (3, 'MacBook Air M4 13 inch', 27990000,
     '{"brand":"Apple","category":"Laptop","memory":"16GB","storage":"512GB SSD"}'),
    (4, 'ASUS Vivobook 15 OLED', 18990000,
     '{"brand":"ASUS","category":"Laptop","memory":"16GB","storage":"512GB SSD"}'),
    (5, 'Sony WH-1000XM6 Headphones', 9990000,
     '{"brand":"Sony","category":"Audio","connection":"Bluetooth","noiseCancelling":"Active"}'),
    (6, 'Logitech MX Master 3S Mouse', 2490000,
     '{"brand":"Logitech","category":"Accessory","connection":"Bluetooth","warranty":"12 months"}'),
    (7, 'Keychron K8 Pro Mechanical Keyboard', 2290000,
     '{"brand":"Keychron","category":"Accessory","layout":"TKL","switch":"Gateron Brown"}'),
    (8, 'Philips HD9252 Air Fryer', 2190000,
     '{"brand":"Philips","category":"Home Appliance","capacity":"4.1L","power":"1400W"}'),
    (9, 'Xiaomi Smart Air Purifier 4', 3990000,
     '{"brand":"Xiaomi","category":"Home Appliance","coverage":"48m2","filter":"HEPA"}'),
    (10, 'Clean Code', 420000,
     '{"author":"Robert C. Martin","category":"Book","language":"English","format":"Paperback"}'),
    (11, 'Nike Air Zoom Pegasus 41', 3490000,
     '{"brand":"Nike","category":"Running Shoes","color":"White and Blue","gender":"Unisex"}'),
    (12, 'LocknLock Metro King Thermal Bottle', 690000,
     '{"brand":"LocknLock","category":"Kitchen","capacity":"1L","material":"Stainless Steel"}'),
    (13, 'Dell XPS 14', 45990000,
     '{"brand":"Dell","category":"Laptop","memory":"32GB","storage":"1TB SSD"}'),
    (14, 'Lenovo ThinkPad X1 Carbon', 42990000,
     '{"brand":"Lenovo","category":"Laptop","memory":"32GB","storage":"1TB SSD"}'),
    (15, 'iPad Air M3 11 inch', 16990000,
     '{"brand":"Apple","category":"Tablet","storage":"128GB","connection":"Wi-Fi"}'),
    (16, 'Samsung Galaxy Tab S10 Plus', 24990000,
     '{"brand":"Samsung","category":"Tablet","storage":"256GB","display":"AMOLED"}'),
    (17, 'Apple Watch Series 10', 10990000,
     '{"brand":"Apple","category":"Smartwatch","size":"46mm","connection":"GPS"}'),
    (18, 'Garmin Forerunner 265', 11990000,
     '{"brand":"Garmin","category":"Smartwatch","sport":"Running","waterResistance":"5 ATM"}'),
    (19, 'AirPods Pro 2', 5990000,
     '{"brand":"Apple","category":"Audio","connection":"Bluetooth","noiseCancelling":"Active"}'),
    (20, 'JBL Charge 6 Speaker', 4490000,
     '{"brand":"JBL","category":"Audio","connection":"Bluetooth","waterResistance":"IP67"}'),
    (21, 'LG UltraGear 27GP850 Monitor', 8990000,
     '{"brand":"LG","category":"Monitor","size":"27 inch","refreshRate":"180Hz"}'),
    (22, 'Samsung Odyssey G5 Monitor', 7490000,
     '{"brand":"Samsung","category":"Monitor","size":"27 inch","resolution":"QHD"}'),
    (23, 'Logitech Brio 4K Webcam', 4290000,
     '{"brand":"Logitech","category":"Accessory","resolution":"4K","connection":"USB-C"}'),
    (24, 'Elgato Wave 3 Microphone', 3990000,
     '{"brand":"Elgato","category":"Audio","type":"Condenser","connection":"USB-C"}'),
    (25, 'Anker 737 Power Bank', 3690000,
     '{"brand":"Anker","category":"Accessory","capacity":"24000mAh","power":"140W"}'),
    (26, 'UGREEN Nexode 100W Charger', 1890000,
     '{"brand":"UGREEN","category":"Accessory","power":"100W","ports":"4"}'),
    (27, 'WD Black SN850X 2TB SSD', 4290000,
     '{"brand":"Western Digital","category":"Storage","capacity":"2TB","interface":"PCIe 4.0"}'),
    (28, 'Samsung T7 Shield 2TB', 4990000,
     '{"brand":"Samsung","category":"Storage","capacity":"2TB","connection":"USB-C"}'),
    (29, 'TP-Link Archer AX73 Router', 2990000,
     '{"brand":"TP-Link","category":"Networking","standard":"Wi-Fi 6","speed":"AX5400"}'),
    (30, 'Synology DS224 Plus NAS', 8990000,
     '{"brand":"Synology","category":"Storage","driveBays":"2","memory":"2GB"}'),
    (31, 'Dyson V12 Detect Slim Vacuum', 14990000,
     '{"brand":"Dyson","category":"Home Appliance","type":"Cordless","runtime":"60 minutes"}'),
    (32, 'Roborock Qrevo S Robot Vacuum', 15990000,
     '{"brand":"Roborock","category":"Home Appliance","navigation":"LiDAR","mopping":"Yes"}'),
    (33, 'Panasonic Inverter Microwave', 4590000,
     '{"brand":"Panasonic","category":"Kitchen","capacity":"25L","power":"1000W"}'),
    (34, 'Electrolux UltimateCare Washing Machine', 12990000,
     '{"brand":"Electrolux","category":"Home Appliance","capacity":"10kg","type":"Front Load"}'),
    (35, 'Instant Pot Duo 7-in-1', 2990000,
     '{"brand":"Instant Pot","category":"Kitchen","capacity":"5.7L","programs":"13"}'),
    (36, 'Kindle Paperwhite', 4290000,
     '{"brand":"Amazon","category":"E-reader","storage":"16GB","display":"7 inch"}'),
    (37, 'The Pragmatic Programmer', 520000,
     '{"author":"David Thomas and Andrew Hunt","category":"Book","language":"English","format":"Paperback"}'),
    (38, 'Designing Data-Intensive Applications', 690000,
     '{"author":"Martin Kleppmann","category":"Book","language":"English","format":"Paperback"}'),
    (39, 'Atomic Habits', 280000,
     '{"author":"James Clear","category":"Book","language":"English","format":"Paperback"}'),
    (40, 'Thinking Fast and Slow', 350000,
     '{"author":"Daniel Kahneman","category":"Book","language":"English","format":"Paperback"}'),
    (41, 'Adidas Ultraboost 5', 4290000,
     '{"brand":"Adidas","category":"Running Shoes","color":"Core Black","gender":"Unisex"}'),
    (42, 'Yonex Astrox 88D Pro', 4890000,
     '{"brand":"Yonex","category":"Badminton","weight":"4U","balance":"Head Heavy"}'),
    (43, 'Decathlon Comfort Yoga Mat', 890000,
     '{"brand":"Decathlon","category":"Fitness","thickness":"8mm","material":"TPE"}'),
    (44, 'Garmin Index S2 Smart Scale', 3990000,
     '{"brand":"Garmin","category":"Fitness","connection":"Wi-Fi","metrics":"Body Composition"}'),
    (45, 'IKEA Markus Office Chair', 4990000,
     '{"brand":"IKEA","category":"Furniture","material":"Mesh","color":"Black"}'),
    (46, 'Xiaomi Electric Standing Desk', 7990000,
     '{"brand":"Xiaomi","category":"Furniture","width":"140cm","heightAdjustment":"Electric"}'),
    (47, 'Moleskine Classic Notebook', 590000,
     '{"brand":"Moleskine","category":"Stationery","size":"Large","paper":"Ruled"}'),
    (48, 'Pilot Custom 74 Fountain Pen', 3290000,
     '{"brand":"Pilot","category":"Stationery","nib":"14K Gold","color":"Black"}'),
    (49, 'LEGO Technic Mercedes-AMG F1', 5690000,
     '{"brand":"LEGO","category":"Toy","pieces":"1642","recommendedAge":"18+"}'),
    (50, 'Nintendo Switch OLED', 8990000,
     '{"brand":"Nintendo","category":"Gaming","storage":"64GB","display":"7 inch OLED"}');
