INSERT IGNORE INTO products (id, name, price, attributes)
VALUES
    (1, 'iPhone 16 Pro', 28990000,
     '{"brand":"Apple","color":"Natural Titanium","storage":"256GB","warranty":"12 months"}'),
    (2, 'Samsung Galaxy S25 Ultra', 26990000,
     '{"brand":"Samsung","color":"Titanium Black","storage":"256GB","warranty":"12 months"}'),
    (3, 'MacBook Air M4 13 inch', 27990000,
     '{"brand":"Apple","color":"Midnight","memory":"16GB","storage":"512GB SSD"}'),
    (4, 'ASUS Vivobook 15 OLED', 18990000,
     '{"brand":"ASUS","processor":"Intel Core Ultra 5","memory":"16GB","storage":"512GB SSD"}'),
    (5, 'Sony WH-1000XM6 Headphones', 9990000,
     '{"brand":"Sony","color":"Black","connection":"Bluetooth","noiseCancelling":"Active"}'),
    (6, 'Logitech MX Master 3S Mouse', 2490000,
     '{"brand":"Logitech","color":"Graphite","connection":"Bluetooth","warranty":"12 months"}'),
    (7, 'Keychron K8 Pro Mechanical Keyboard', 2290000,
     '{"brand":"Keychron","layout":"TKL","switch":"Gateron Brown","connection":"Bluetooth and USB-C"}'),
    (8, 'Philips HD9252 Air Fryer', 2190000,
     '{"brand":"Philips","capacity":"4.1L","power":"1400W","warranty":"24 months"}'),
    (9, 'Xiaomi Smart Air Purifier 4', 3990000,
     '{"brand":"Xiaomi","coverage":"48m2","filter":"HEPA","connection":"Wi-Fi"}'),
    (10, 'Clean Code', 420000,
     '{"author":"Robert C. Martin","language":"English","format":"Paperback","category":"Software Engineering"}'),
    (11, 'Nike Air Zoom Pegasus 41', 3490000,
     '{"brand":"Nike","color":"White and Blue","category":"Running","gender":"Unisex"}'),
    (12, 'LocknLock Metro King Thermal Bottle', 690000,
     '{"brand":"LocknLock","capacity":"1L","material":"Stainless Steel","color":"Ivory"}');
