spring:
  application:
    name: notification-service
  datasource:
    url: "${DB_URL:jdbc:mariadb://localhost:3306/ecommerce_db}"
    username: "${DB_USERNAME:app_user}"
    password: "${DB_PASSWORD:password}"
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084
